export const bodyParts = [
  { value: '', label: 'Body parts: All' },
  { value: 'back', label: 'Back' },
  { value: 'cardio', label: 'Cardio' },
  { value: 'chest', label: 'Chest' },
  { value: 'lower arms', label: 'Lower Arms' },
  { value: 'lower legs', label: 'Lower Legs' },
  { value: 'neck', label: 'Neck' },
  { value: 'shoulders', label: 'Shoulders' },
  { value: 'upper arms', label: 'Upper Arms' },
  { value: 'upper legs', label: 'Upper Legs' },
  { value: 'waist', label: 'Waist' },
];

export const equipments = [
  { value: '', label: 'Equipment: All' },
  { value: 'assisted', label: 'Assisted' },
  { value: 'band', label: 'Band' },
  { value: 'barbell', label: 'Barbell' },
  { value: 'bosu ball', label: 'Bosu Ball' },
  { value: 'body weight', label: 'Body Weight' },
  { value: 'cable', label: 'Cable' },
  { value: 'dumbbell', label: 'Dumbbell' },
  { value: 'elliptical machine', label: 'Elliptical Machine' },
  { value: 'ez barbell', label: 'EZ Barbell' },
  { value: 'hammer', label: 'Hammer' },
  { value: 'kettlebell', label: 'Kettlebell' },
  { value: 'leverage machine', label: 'Leverage Machine' },
  { value: 'medicine ball', label: 'Medicine Ball' },
  { value: 'olympic barbell', label: 'Olympic Barbell' },
  { value: 'resistance band', label: 'Resistance Band' },
  { value: 'roller', label: 'Roller' },
  { value: 'rope', label: 'Rope' },
  { value: 'sled machine', label: 'Sled Machine' },
  { value: 'smith machine', label: 'Smith Machine' },
  { value: 'skierg machine', label: 'Skierg Machine' },
  { value: 'stability ball', label: 'Stability Ball' },
  { value: 'stepmill machine', label: 'Stepmill Machine' },
  { value: 'stationary bike', label: 'Stationary Bike' },
  { value: 'tire', label: 'Tire' },
  { value: 'trap bar', label: 'Trap Bar' },
  { value: 'upper body ergometer', label: 'Upper Body Ergometer' },
  { value: 'weighted', label: 'Weighted' },
  { value: 'wheel roller', label: 'Wheel Roller' },
];

export const targets = [
  { value: '', label: 'Target: All' },
  { value: 'abs', label: 'Abs' },
  { value: 'abductors', label: 'Abductors' },
  { value: 'adductors', label: 'Adductors' },
  { value: 'biceps', label: 'Biceps' },
  { value: 'calves', label: 'Calves' },
  { value: 'cardiovascular system', label: 'Cardiovascular System' },
  { value: 'delts', label: 'Delts' },
  { value: 'forearms', label: 'Forearms' },
  { value: 'glutes', label: 'Glutes' },
  { value: 'hamstrings', label: 'Hamstrings' },
  { value: 'lats', label: 'Lats' },
  { value: 'levator scapulae', label: 'Levator Scapulae' },
  { value: 'pectorals', label: 'Pectorals' },
  { value: 'quads', label: 'Quads' },
  { value: 'serratus anterior', label: 'Serratus Anterior' },
  { value: 'spine', label: 'Spine' },
  { value: 'traps', label: 'Traps' },
  { value: 'triceps', label: 'Triceps' },
  { value: 'upper back', label: 'Upper Back' },
];
